# Generated by Django 5.2.4 on 2025-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(max_length=255, verbose_name='مدل گوشی')),
                ('color_prices', models.JSONField(default=dict, verbose_name='قیمت بر اساس رنگ')),
                ('warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='گارانتی')),
                ('stock', models.CharField(blank=True, max_length=50, null=True, verbose_name='موجودی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('source_site', models.CharField(choices=[('IL', 'آیلندینو'), ('DZ', 'دیزولند'), ('IP', 'ایران پاور'), ('GL', 'گرین لاین')], max_length=2, verbose_name='منبع سایت')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس محصول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'unique_together': {('source_site', 'url')},
            },
        ),
    ]
